### ISSUE TITLE
WORDLE game

### ISSUE THREAD

**Issue by sid-am-ahd935** [Subhradeep10/Automation-Scripts-Using-Python#107]
Hi @Subhradeep10 will you assign me this issue, I will start working on it right away.

**Comment by Subhradeep10** [comment]
@sid-am-ahd935 Assign to you, Go ahead

**Comment by surreal30** [comment]
Can I try it too?

**Comment by Subhradeep10** [comment]
@surreal30 No create another issue, and I will assign it to you
