### ISSUE TITLE
Realtime-chat-app-using-Python

### ISSUE THREAD

**Issue by Xester22** [Subhradeep10/Automation-Scripts-Using-Python#135]
# Realtime-chat-app-using-Python
Chat Room has been the most basic step toward creating real-time and live projects. The chat page that we will create will be a simple HTML boilerplate with a simple h1 text with the name of the current user and a link to log out to the user who is just logged in. You may need to comment on the line until we create auth system for this

Hope you will like it
and dont forget to add the Hacktober fest label

**Comment by Subhradeep10** [comment]
Create this issue in amazing Web Projects

**Comment by Morbius00** [comment]
> Create this issue in amazing Web Projects

Please share the issue link section
