### ISSUE TITLE
Cryptocurrency price alert using python

### ISSUE THREAD

**Issue by aatharvauti** [Subhradeep10/Automation-Scripts-Using-Python#15]
## A python script that alerts you by opening your portfolio webpage on browser when a cryptocurrency hits a certain price.

Example: If MATIC hits $0.80 or more, it will automatically open a webpage (crypto trade) on the user's browser.

_(it will run in background using cronjob)_

Use case: Crypto prices are highly volatile and there are no stop loss or good alert systems in many exchange platforms. This will help the user to stay updated with the crypto price trend while they do other tasks.

**Comment by aatharvauti** [comment]
I would like to contribute to this code, please assign the issue for the hacktoberfest.

**Comment by Subhradeep10** [comment]
@aatharvauti Great, Go ahead assign to you

**Comment by Subhradeep10** [comment]
@aatharvauti Any updates? otherwise I will close the issue

**Comment by aatharvauti** [comment]
@Subhradeep10 I will update it before afternoon
