### ISSUE TITLE
[add] Bitcoin Address Validator Script using Python

### ISSUE THREAD

**Issue by iSumitBanik** [Subhradeep10/Automation-Scripts-Using-Python#165]
**Overview**

Currently, there's no script present in this repo which checks for the validity for a Bitcoin Address.

- [x] Add a Python Script to check validity for Bitcoin Address

**Comment by Subhradeep10** [comment]
@iSumitBanik assign to you

**Comment by iSumitBanik** [comment]
@Subhradeep10 , PR created #167 

Please feel free to review.
Thanks.
