### ISSUE TITLE
URL Shortener Script using Python

### ISSUE THREAD

**Issue by Debarghya001** [Subhradeep10/Automation-Scripts-Using-Python#2]
@Subhradeep10 assign this to me.

**Comment by Subhradeep10** [comment]
Assigned to you @Debarghya001

**Comment by abhishek8778** [comment]
Is the issue solved  ? if it isn't you can assign it to me i have done  asimilar mini project to this in past so i can help you in this

**Comment by Subhradeep10** [comment]
@abhishek8778 Already assigned
You can create another issue
