### ISSUE TITLE
Web Scraper using Python

### ISSUE THREAD

**Issue by prakrit55** [Subhradeep10/Automation-Scripts-Using-Python#21]
This will be a web scraper to extract data from Web pages and save it on your hard drive.

You visit a website from where you pull data. This code will be handled repeatedly to bring data.  It's a python made application.

**Comment by prakrit55** [comment]
If this is accepted please assign me.

**Comment by Subhradeep10** [comment]
@prakrit55 Assigned to you

**Comment by Ksj14-kumar** [comment]
Please assign me this issue...

**Comment by Subhradeep10** [comment]
@Ksj14-kumar It is assigned to someone else,if he don't respond in 3-4 days..Then I will assign it to you..
Till then you can create your own valid issue

**Comment by Ksj14-kumar** [comment]
Ok

**Comment by prakrit55** [comment]
Pls  @Subhradeep10  I'm  on this issue.
Its getting done right in an hour.
