### ISSUE TITLE
Email Validator using Python

### ISSUE THREAD

**Issue by smit-sms** [Subhradeep10/Automation-Scripts-Using-Python#33]
This will be a script that takes input as an email address and checks whether the email address is valid or not. 
It contains checking static email address format as well as smtp server checking.

**Comment by smit-sms** [comment]
Please assign this to me as a part of hacktoberfest event. @Subhradeep10

**Comment by Subhradeep10** [comment]
@smit-sms Assign to you, Go ahead

Give a star 🌟, if you like the repo
