### ISSUE TITLE
Unit Conveter

### ISSUE THREAD

**Issue by SirRomey** [Subhradeep10/Automation-Scripts-Using-Python#36]
Convert units in the metric system using a simple python script.

**Comment by Subhradeep10** [comment]
@SirRomey Assign to you

**Comment by SHASHWAT-SGH** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by SirRomey** [comment]
> I want to work on this issue. Please assign this issue to me.

I've already pushed the code. You can perhaps improve upon it if the repo maintainer agrees.

**Comment by Sonal-Maurya** [comment]
I want to contribute to it

**Comment by DebdattaRay** [comment]
I want to contribute to your issue. This is my first time participating and contributing. Please assign me this issue. Thank You

**Comment by Subhradeep10** [comment]
@DebdattaRay You can go ahead
