### ISSUE TITLE
RGB Image to Grayscale Image Converter

### ISSUE THREAD

**Issue by HVbajoria** [Subhradeep10/Automation-Scripts-Using-Python#43]
I wish to add a python script that can be used to convert images in RGB to a grayscale image.

Could you please assign me this issue so that I may contribute. 
Thank you
Happy HacktoberFest!

**Comment by Subhradeep10** [comment]
@HVbajoria Assign to you, Go ahead 

Star 🌟 the repo if you liked it
Happy Hacktoberfest 🚀
