### ISSUE TITLE
Want to add a Rock, Paper, Scissor game and a Password generator

### ISSUE THREAD

**Issue by dasrahul505** [Subhradeep10/Automation-Scripts-Using-Python#88]

**Comment by Subhradeep10** [comment]
@dasrahul505 Rock paper scissors is already there, you can go ahead with password generator

**Comment by dasrahul505** [comment]
Okay

**Comment by govkartha** [comment]
@dasrahul505 @Subhradeep10 Can I do an alternative solution to password generator?

**Comment by Subhradeep10** [comment]
@govkartha Better create another issue
