### ISSUE TITLE
Acronyms using python

### ISSUE THREAD

**Issue by Laraibnehal** [Subhradeep10/Automation-Scripts-Using-Python#9]
Acronyms are shortened forms of word  or phrases. They assist in making manuscripts easy to read and understand. Additionally, they help in meeting the strict word-count targets, avoiding the repetition of words, thereby making the text easy to read.

**Comment by Laraibnehal** [comment]
Assign me this issue

**Comment by Subhradeep10** [comment]
@Laraibnehal Assigned to you
